config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'aline' => 'alines#aline'
  resources :users,only: [:show,:index,:edit,:update] do
    member do
    get :search
    get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end


end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @post_comment = current_user.post_comments.new(post_comment_params)
    @post_comment.book_id = @book.id
    if @post_comment.save
      render :post_comments
    else
      render :error
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    post_comment = @book.post_comments.find(params[:id])
    post_comment.destroy
    render :post_comments
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)

  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_comments.html.erb
    <% if book.post_comments.present? %>
      <table class="table">
        <tbody>
          <% book.post_comments.each do |post_comment| %>
          <tr>
            <td>
              <%= attachment_image_tag(post_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
              <%= link_to post_comment.user.name, user_path(post_comment.user) %>
            </td>
            <td>
              <%= post_comment.comment %>
            </td>
            <% if post_comment.user == current_user %>
            <td>
              <%= link_to book_post_comment_path(post_comment.book, post_comment), method: :delete, remote: true do %>
                <button class="btn btn-sm btn-danger destroy_book_#{@book.id}">Destroy</button>
              <% end %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>コメントはまだありません</p>
    <% end %>

app/views/post_comments/_form.html.erb
<%= form_with model:[book, post_comment] do |f| %>
  <div id="comments_error">
    <%= render 'layouts/errors', obj: f.object %>
  </div>
  <div class="form-group">
    <%= f.text_area :comment,  class: 'form-control', rows: 5%>
  </div>
  <%= f.submit "送信" %>
<% end %>

app/views/post_comments/error.js.erb
$("#comments_error").html("<%= j(render 'layouts/errors', obj: @post_comment) %>");

app/views/post_comments/post_comments.js.erb
$("#comments_index").html("<%= j(render 'post_comments/comments', book: @book, post_comment: @post_comment) %>");
$("textarea").val('');