config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'aline' => 'alines#aline'
  resources :users,only: [:show,:index,:edit,:update] do
    member do
    get :search
    get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books.order(created_at: :DESC)
    @book = Book.new
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def index
    @users = User.all.order(created_at: :DESC)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless current_user == @user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.following_user.all
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.follower_user.all
  end

  def search
    @user = User.find(params[:id])
    @books =@user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日時を選択してください"
    else
      created_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ?', "#{created_at}%"]).count
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_graph.html.erb
<canvas id="weekry_post"></canvas>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
<script>
$(document).on('turbolinks:load', function() {
  let ctx = document.getElementById("weekry_post");
  let weekry_post = new Chart(ctx, {
    type: 'line',
    data: {
      labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
      datasets: [
        {
          label: '投稿数',
          data: [
                  <%= books.where(created_at: 6.day.ago.all_day).count %>,
                  <%= books.where(created_at: 5.day.ago.all_day).count %>,
                  <%= books.where(created_at: 4.day.ago.all_day).count %>,
                  <%= books.where(created_at: 3.day.ago.all_day).count %>,
                  <%= books.where(created_at: 2.day.ago.all_day).count %>,
                  <%= books.where(created_at: 1.day.ago.all_day).count %>,
                  <%= books.where(created_at: Time.zone.now.all_day).count %>
          ],
          borderColor: "#0000ff",
          backgroundColor: "rgba(0,0,0,0)"

        }
      ],
    },
    options: {
      title: {
        display: true,
        text: '今週の投稿数の推移'
      },
       scales: {
        yAxes: [{
          ticks: {
            suggestedMax: 10,
            suggestedMin: 0,
            stepSize: 1,
            callback: function(value, index, values){
              return value + '本'
            }
          }
        }]
      },
    }
  });
});
</script>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.following_user.count %></td>
        <td>フォロワー数:<%= user.follower_user.count %></td>
        <td>
          <% if user == current_user %>

          <% else %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォローを外す',user_relationships_path(user), method: :delete %>
            <% else %>
              <%= link_to 'フォローする',user_relationships_path(user), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>followings</th>
    <th>
      <%= link_to follows_user_path(user) do %>
        <%= user.following_user.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to followers_user_path(user) do%>
          <%= user.follower_user.count %>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <% if user == current_user %>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= link_to 'フォローを外す',user_relationships_path(user), method: :delete, class: "btn btn-info btn-block" %>
    <% else %>
      <%= link_to 'フォローする',user_relationships_path(user), method: :post, class: "btn btn-success btn-block" %>
    <% end %>
  <% end %>
</div>

app/views/users/_post_count.html.erb
 <h2>投稿数の前日比・前週比</h2>
  <table border="1" class="table">
    <tr>
      <th class="col-4">今日の投稿数</th>
      <th class="col-4">前日の投稿数</th>
      <th class="col-3">前日比</th>
    </tr>
    <tr>
      <td><%= books.created_today.count %></td>
      <td><%= books.created_yesterday.count %></td>
      <td>
        <% @the_day_before = books.created_today.count / books.created_yesterday.count.to_f %>
        <% if books.created_today.count == 0 || books.created_yesterday.count == 0 %>
          前日比はありません
        <% else %>
          <%= (@the_day_before * 100).round %>%
        <% end %>
      </td>
    </tr>
  </table>
  <table border="1" class="table">
    <tr>
      <th class="col-4">今週の投稿数</th>
      <th class="col-4">先週の投稿数</th>
      <th class="col-3">前週比</th>
    </tr>
    <tr>
      <td><%= books.created_thisweek.count %></td>
      <td><%= books.created_lastweek.count %></td>
      <td>
        <% @the_week_befor = books.created_thisweek.count / books.created_lastweek.count.to_f %>
        <% if books.created_thisweek.count == 0 || books.created_lastweek.count == 0 %>
          前週比はありません
        <% else %>
          <%= (@the_week_befor * 100).round %>%
        <% end %>
      </td>
    </tr>
  </table>

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr> 
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/_weekry_post_count.html.erb
<h2>7日間分の投稿数</h2>
<table class="table table-bordered col">
  <tr>
    <th>６日前</th>
    <th>５日前</th>
    <th>４日前</th>
    <th>３日前</th>
    <th>２日前</th>
    <th>１日前</th>
    <th>今日</th>
  </tr>
  <tr>
    <td><%= books.where(created_at: 6.day.ago.all_day).count %></td>
    <td><%= books.where(created_at: 5.day.ago.all_day).count %></td>
    <td><%= books.where(created_at: 4.day.ago.all_day).count %></td>
    <td><%= books.where(created_at: 3.day.ago.all_day).count %></td>
    <td><%= books.where(created_at: 2.day.ago.all_day).count %></td>
    <td><%= books.where(created_at: 1.day.ago.all_day).count %></td>
    <td><%= books.where(created_at: Time.zone.now.all_day).count %></td>
  </tr>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Follower Users</h1>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>followings</h1>
      <%= render 'users/index', users: @users %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8">
      <h2>Users</h2>
      <%= render 'index',users: @users %>

    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'users/search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <%= render 'users/post_count', books: @books %>
      <%= render 'users/weekry_post_count', books: @books %>
      <%= render 'users/graph', books: @books %>
      <%= form_with url: search_user_path(@user), class: "mt-3", method: :get do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit "検索", class: 'btn btn-primary' %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <% render 'users/serch', search_book %>
        <% end %>
      </div>
    </div>
  </div>
</div>