config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#about'
  get 'search' => 'searches#search'
  get 'aline' => 'alines#aline'
  resources :users,only: [:show,:index,:edit,:update] do
    member do
    get :search
    get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end


end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :book_tags, dependent: :destroy
	has_many :tags, through: :book_tags

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

  scope :created_today, -> {where(created_at: Time.zone.now.all_day)}
  scope :created_yesterday, -> {where(created_at: 1.day.ago.all_day)}
  scope :created_thisweek, -> {where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day)}
  scope :created_lastweek, -> {where(created_at: 2.week.ago.end_of_day..1.week.ago.end_of_day)}
  
	def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

  def self.sort(selection)
    case selection
    when 'new'
      return Book.all.order(created_at: :DESC)
    when 'old'
      return Book.all.order(created_at: :ASC)
    when 'like'
      return Book.all.order(rate: :DESC)
    when 'dislike'
      return Book.all.order(rate: :ASC)
    end
  end

  def tags_save(tag_list)
    if self.tags != nil
      book_tags_records = BookTag.where(book_id: self.id)
      book_tags_records.destroy_all
    end

    tag_list.each do |tag|
      inspected_tag = Tag.where(tag_name: tag).first_or_create
      self.tags << inspected_tag
    end

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @post_comment = PostComment.new
  end

  def index
    @book = Book.new
    @books = Book.all.order(created_at: :DESC)
  end

  def tag_index
    @book = Book.new
    tag = Tag.find(params[:id])
    @books = tag.books.order(created_at: :DESC)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list = params[:book][:tag_name].split(",")
    if @book.save
      @book.tags_save(tag_list)
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to user_path(current_user) unless current_user == @book.user
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :tag_name %>
    <%= f.text_field :tag_name, placeholder:",で区切ってください" %>
  </div>
  <% if book.id ===nil %>
  <div class="form-group" id="star">
    <label>評価：</label>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
  <% else %>
  <td>
    <%= render 'books/star', book: book %>
  </td>
  <% end %>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>
<script>
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'book[rate]',
    half: true,
  });
</script>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td id="favorite_buttons_<%= book.id %>">
          <%= render 'favorites/favorite', book: book %>
        </td>
        <td>
          <p>コメント数：<%= book.post_comments.count %></p>
        </td>
        <td>
          <%= render 'books/star', book: book %>
        </td>
      </tr>
      <%= render 'books/tag', book: book %>
    <% end %>
  </tbody>
</table>

app/views/books/_star.html.erb
<div id="star-rate-<%= book.id %>"></div>
  <script>
  $('#star-rate-<%= book.id %>').raty({
    size: 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= book.rate %>,
  });
  </script>

app/views/books/_tag.html.erb
 <tr>
    <td>Tags:</td>
    <% book.tags.each do |tag| %>
      <td>
        <%=link_to tag.tag_name, search_path(word: tag.tag_name, range: "Tag", search: "perfect_match") %>
      </td>
    <% end %>
  </tr>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'books/form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <%= render 'layouts/errors', obj: @book %>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'alines/aline' %>
      <div id="aline_books">
      <%= render 'index', books: @books%>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td id="favorite_buttons_<%= @book.id %>">
              <%= render 'favorites/favorite', book: @book %>
          </td>
          <td>
            <p>コメント数：<%= @book.post_comments.count %></p>
          </td>
          <td>
            <%= render 'books/star', book: @book %>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
        <%= render 'books/tag', book: @book %>
      </table>
      <div id="comments_index">
        <%= render 'post_comments/comments', book: @book %>
      </div>
      <div>
        <%= render 'post_comments/form', book: @book, post_comment: @post_comment %>
      </div>

    </div>
  </div>
</div>